# Site settings
title: Adam Kozlowski
url: https://kozload.github.io
description: "Physician Scientist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Adam Kozlowski

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:amv.kozlowski@gmail.com
  - title: github
    url: https://github.com/kozload

# Build settings
markdown: kramdown
permalink: pretty
